### ISSUE TITLE
[TO-DO] Your general TO-DO list

### ISSUE THREAD

**Issue by RealAkito** [RaphielGang/Telegram-Paperplane#231]
### Project's Current TO-DO

- [ ] Integrate Kantek with Paperplane
- [ ] Make the mute command check if the user can delete messages in a group before saying they are not an admin
- [ ] Save alive username in DB
- [ ] Check if config properties like botlog_chatid are valid when starting the userbot
- [ ] Don't say "kicking away" in welcome mute when not admin
- [ ] .weather command API Key NoneType has no len()
- [ ] Improve sleep
- [ ] Make welcome mute check if there was a report command(or @ admin) before reporting someone
- [ ] Check the shit happening with .download, test link: https://ci.android.com/builds/submitted/5848636/aosp_arm64-eng/latest/super.img
- [ ] Proper error checking, less editing in .block
- [ ] Fix .restart not restarting when not being run in Docker
- [ ] Fix some of the Lists module's commands logger messages

This **TO-DO** list will be kept updated. Please always take a look at this post.

**Comment by RealAkito** [comment]
So, this is the concept.
All "approved" feature requests will get added to the project's TO-DO list.
This way, we keep track of what we are supposed to do and don't get messed up.

**Comment by RealAkito** [comment]
Please, do not report bug(s) or request feature(s) here, make a separate issue.

**Comment by theRay1s** [comment]
Add Gdrive Search Feature to @RealAkito
